/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Id = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Episode = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'showId' : Id,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'videoBlob' : IDL.Opt(ExternalBlob),
  'seasonNumber' : IDL.Nat,
  'episodeNumber' : IDL.Nat,
});
export const Show = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'creatorId' : IDL.Principal,
  'description' : IDL.Text,
  'thumbnailBlob' : IDL.Opt(ExternalBlob),
  'isFeatured' : IDL.Bool,
  'genre' : IDL.Text,
  'isPublic' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const EpisodeProgress = IDL.Record({
  'episodeId' : Id,
  'updatedAt' : IDL.Int,
  'timestamp' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWatchlist' : IDL.Func([Id], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEpisode' : IDL.Func(
      [
        Id,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Nat,
      ],
      [Episode],
      [],
    ),
  'createShow' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
      [Show],
      [],
    ),
  'deleteEpisode' : IDL.Func([Id], [], []),
  'deleteShow' : IDL.Func([Id], [], []),
  'getAllShows' : IDL.Func([IDL.Bool], [IDL.Vec(Show)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContinueWatching' : IDL.Func([], [IDL.Vec(EpisodeProgress)], ['query']),
  'getEpisode' : IDL.Func([Id], [Episode], ['query']),
  'getEpisodesBySeason' : IDL.Func(
      [Id, IDL.Nat],
      [IDL.Vec(Episode)],
      ['query'],
    ),
  'getEpisodesByShow' : IDL.Func([Id], [IDL.Vec(Episode)], ['query']),
  'getFeaturedShow' : IDL.Func([], [IDL.Opt(Show)], ['query']),
  'getShow' : IDL.Func([Id], [Show], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(Id)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromWatchlist' : IDL.Func([Id], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEpisodeProgress' : IDL.Func([Id, IDL.Nat], [], []),
  'searchShows' : IDL.Func([IDL.Text], [IDL.Vec(Show)], ['query']),
  'updateEpisode' : IDL.Func(
      [
        Id,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateShow' : IDL.Func(
      [
        Id,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Id = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Episode = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'showId' : Id,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'videoBlob' : IDL.Opt(ExternalBlob),
    'seasonNumber' : IDL.Nat,
    'episodeNumber' : IDL.Nat,
  });
  const Show = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'creatorId' : IDL.Principal,
    'description' : IDL.Text,
    'thumbnailBlob' : IDL.Opt(ExternalBlob),
    'isFeatured' : IDL.Bool,
    'genre' : IDL.Text,
    'isPublic' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const EpisodeProgress = IDL.Record({
    'episodeId' : Id,
    'updatedAt' : IDL.Int,
    'timestamp' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWatchlist' : IDL.Func([Id], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEpisode' : IDL.Func(
        [
          Id,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Nat,
        ],
        [Episode],
        [],
      ),
    'createShow' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool],
        [Show],
        [],
      ),
    'deleteEpisode' : IDL.Func([Id], [], []),
    'deleteShow' : IDL.Func([Id], [], []),
    'getAllShows' : IDL.Func([IDL.Bool], [IDL.Vec(Show)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContinueWatching' : IDL.Func([], [IDL.Vec(EpisodeProgress)], ['query']),
    'getEpisode' : IDL.Func([Id], [Episode], ['query']),
    'getEpisodesBySeason' : IDL.Func(
        [Id, IDL.Nat],
        [IDL.Vec(Episode)],
        ['query'],
      ),
    'getEpisodesByShow' : IDL.Func([Id], [IDL.Vec(Episode)], ['query']),
    'getFeaturedShow' : IDL.Func([], [IDL.Opt(Show)], ['query']),
    'getShow' : IDL.Func([Id], [Show], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(Id)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromWatchlist' : IDL.Func([Id], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEpisodeProgress' : IDL.Func([Id, IDL.Nat], [], []),
    'searchShows' : IDL.Func([IDL.Text], [IDL.Vec(Show)], ['query']),
    'updateEpisode' : IDL.Func(
        [
          Id,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateShow' : IDL.Func(
        [
          Id,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };