/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Episode {
  'id' : Id,
  'title' : string,
  'duration' : bigint,
  'showId' : Id,
  'createdAt' : bigint,
  'description' : string,
  'videoBlob' : [] | [ExternalBlob],
  'seasonNumber' : bigint,
  'episodeNumber' : bigint,
}
export interface EpisodeProgress {
  'episodeId' : Id,
  'updatedAt' : bigint,
  'timestamp' : bigint,
}
export type ExternalBlob = Uint8Array;
export type Id = bigint;
export interface Show {
  'id' : Id,
  'title' : string,
  'createdAt' : bigint,
  'creatorId' : Principal,
  'description' : string,
  'thumbnailBlob' : [] | [ExternalBlob],
  'isFeatured' : boolean,
  'genre' : string,
  'isPublic' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToWatchlist' : ActorMethod<[Id], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEpisode' : ActorMethod<
    [Id, bigint, bigint, string, string, [] | [ExternalBlob], bigint],
    Episode
  >,
  'createShow' : ActorMethod<
    [string, string, string, [] | [ExternalBlob], boolean],
    Show
  >,
  'deleteEpisode' : ActorMethod<[Id], undefined>,
  'deleteShow' : ActorMethod<[Id], undefined>,
  'getAllShows' : ActorMethod<[boolean], Array<Show>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContinueWatching' : ActorMethod<[], Array<EpisodeProgress>>,
  'getEpisode' : ActorMethod<[Id], Episode>,
  'getEpisodesBySeason' : ActorMethod<[Id, bigint], Array<Episode>>,
  'getEpisodesByShow' : ActorMethod<[Id], Array<Episode>>,
  'getFeaturedShow' : ActorMethod<[], [] | [Show]>,
  'getShow' : ActorMethod<[Id], Show>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWatchlist' : ActorMethod<[], Array<Id>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromWatchlist' : ActorMethod<[Id], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEpisodeProgress' : ActorMethod<[Id, bigint], undefined>,
  'searchShows' : ActorMethod<[string], Array<Show>>,
  'updateEpisode' : ActorMethod<
    [Id, bigint, bigint, string, string, [] | [ExternalBlob], bigint],
    undefined
  >,
  'updateShow' : ActorMethod<
    [Id, string, string, string, [] | [ExternalBlob], boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];